namespace MySharpDivert.Native.Enums
{
	public enum ChecksumCalcFlags
	{
		NONE = 0,
		WINDIVERT_HELPER_NO_IP_CHECKSUM = 1,
		WINDIVERT_HELPER_NO_ICMP_CHECKSUM = 2,
		WINDIVERT_HELPER_NO_ICMPV6_CHECKSUM = 4,
		WINDIVERT_HELPER_NO_TCP_CHECKSUM = 8,
		WINDIVERT_HELPER_NO_UDP_CHECKSUM = 16
	}
}
