namespace MySharpDivert.Native
{
	public enum WinDivertLayer : int
	{
		WINDIVERT_LAYER_NETWORK = 0,
		WINDIVERT_LAYER_NETWORK_FORWARD,
		WINDIVERT_LAYER_FLOW,
		WINDIVERT_LAYER_SOCKET,
		WINDIVERT_LAYER_REFLECT,
	}
}
