namespace MySharpDivert.Native.Enums
{
	internal enum WinDivertShutdown
	{
		WINDIVERT_SHUTDOWN_RECV = 1,
		WINDIVERT_SHUTDOWN_SEND = 2,
		WINDIVERT_SHUTDOWN_BOTH = WINDIVERT_SHUTDOWN_RECV | WINDIVERT_SHUTDOWN_SEND
	}
}
